package scanner;

/**
 * The enum of the token types for the expression grammar.
 */
public enum TokenType {

    AND, ARRAY, ASSIGNMENT_OP, BEGIN, COLON, COMMA, DIV, DO,
    EQUALS, ELSE, END, FUNCTION, ID, IF,
    GREATER_THAN, GREATER_THAN_EQUAL_TO,
    LESS_THAN, LESS_THAN_EQUAL_TO,
    INTEGER, MOD, NOT, OF, OR, PROCEDURE, PROGRAM, REAL,
    THEN, VAR, WHILE, SEMI_COLON, PERIOD,
    LEFT_BRACKET, RIGHT_BRACKET, LEFT_PAREN, RIGHT_PAREN,
    PLUS, MINUS, NOT_EQUAL, MULTIPLY, DIVIDE, NUMBER

}